# CrystalBanker Configuration File
# Revision: 1.0.4

# Name of your server's "bank"
bank-name: Bank of CrystalCraftMC

# Use glass bottles? (Glass ability not implemented in code yet)
require-glass: false
