name: CrystalBanker
main: com.crystalcraftmc.crystalbanker.CrystalBanker
version: ${version}
description: Convert XP to bottles, and bottles to XP!
authors: [jflory7, Jacc734, devastator10k]
website: http://crystalcraftmc.com

commands:
  crystalbanker:
    description: Exchange dealing with XP and XP bottles.
    aliases: [banker, ccmcbanker]
    permission: crystalbanker-transaction

permissions:
  crystalbanker.transaction:
    description: Exchange dealing with XP and XP bottles.
    default: true
  crystalbanker.reload:
    description: Reload the configuration file.
    default: op