name: CrystalBanker
main: com.crystalcraftmc.crystalbanker.CrystalBanker
version: 1.0.3
website: http://crystalcraftmc.com
authors: [Jacc734, Jwood9198, jflory7]
description: Nothing like having the power of a bank at your finger tips.

commands:
  crystalbanker:
    description: Cash in at the CrystalBank!
    usage: /crystalbanker <deposit|withdraw|cash> [amount]
    aliases: [banker, ccbanker, cb, xpbank]

permissions:
  crystalbanker.player.*:
    description: All player permissions for CrystalBanker
    children:
      crystalbanker.deposit: true
      crystalbanker.withdraw: true
      crystalbanker.zero: true
  crystalbanker.deposit:
    description: Store levels into bottles.
    default: op
  crystalbanker.withdraw:
    description: Turn bottles into levels.
    default: op
  crystalbanker.zero:
    description: Convert all bottles in inventory to XP.
    default: op
  crystalbanker.reload:
    description: Reload configuration file.
    default: op
