name: CrystalBanker
main: com.crystalcraftmc.crystalbanker.CrystalBanker
version: 1.0.4
description: Convert experience orbs to bottles and bottles to experience orbs.
authors: [jflory7, Jacc734, Jwood9198]
website: https://github.com/CrystalCraftMC/CrystalBanker
api-version: 1.13

commands:
  crystalbanker:
    description: Cash in at the CrystalBank!
    usage: /crystalbanker <deposit|withdraw|zero> [amount]
    aliases: [banker, ccbanker, cb, xpbank]

permissions:
  crystalbanker.player.*:
    description: All player permissions for CrystalBanker
    children:
      crystalbanker.deposit: true
      crystalbanker.withdraw: true
      crystalbanker.zero: true
      crystalbanker.cash: true
  crystalbanker.deposit:
    description: Store levels into bottles.
    default: op
  crystalbanker.withdraw:
    description: Turn bottles into levels.
    default: op
  crystalbanker.zero:
    description: Convert all bottles in inventory to XP.
    default: op
  crystalbanker.cash:
    description: Convert levels to max amount of bottles player's inventory can hold.
    default: op
  crystalbanker.reload:
    description: Reload configuration file.
    default: op
