name: CrystalBanker
main: com.crystalcraftmc.crystalbanker.CrystalBanker
version: 0.0.1
description: Nothing like having the power of a bank at your finger tips.
authors: [Jflory7, Jwood9198, Jacc734]

commands:
 crystalbankerreload:
  description: reload
  aliases: [bankreload, bankR, cbr]
  permission: crystalbanker.reload
 crystalbankerdeposit:
  description: deposit number of levels
  aliases: [bankdeposit, bankD, cbd]
  permission: crystalbanker.deposit
 crystalbankerwithdraw:
  description: withdraw number of bottles
  aliases: [bankwithdraw, bankW, cbw]
  permission: crystalbanker.withdraw
 crystalbankerhcasin:
  description: Cash in all the bottles in your inventory.
  aliases: [cbc, maxlevel, xpmax, cashin]
  permission: crystalbanker.cashin
permissions:
 crystalbanker.deposit:
  description: Store levels into bottles
  default: true
 crystalbanker.withdraw:
  description: Turn bottles into levels
  default: true
 crystalbanker.reload:
  description: Reloads Plugin
  default: op
 crystalbanker.cashin:
  description: Convert all bottles in inventory to xp
  default: true
