name: CrystalBanker
main: com.crystalcraftmc.crystalbanker.CrystalBanker
version: 0.1.1
description: Convert experience orbs to bottles and bottles to experience orbs.
authors: [jflory7, Jacc734, Jwood9198]
website: https://crystalcraftmc.com

commands:
  crystalbanker:
    description: Exchange dealing with XP and XP bottles.
    aliases: [banker, ccmcbanker]
    permission: crystalbanker.transaction

permissions:
  crystalbanker.transaction:
    description: Exchange dealing with experience orbs and experience bottles.
    default: true
  crystalbanker.reload:
    description: Reload the configuration file.
    default: op
